### ISSUE TITLE
Implement the "identities" scope in the IDM Wallet module

### ISSUE THREAD

**Issue by paulobmarcos** [ipfs-shipyard/pm-idm#105]
## Description

Implement the `identities` scope according to the IDM spec.

## Acceptance Criteria

- [x] Use leveldb as the storage, which will support range queries
- [x] Check if we may use the leveldb of the IPFS instance
- [x] Ensure that the identities ~~persisted are encrypted~~, including hashing the DIDs in the keys (e.g.: `identity-shaXXX(DID)`)
   - Check if there's an encryption plugin for leveldb
- [x] Have the `identities` scope of the IDM Wallet implemented

**Comment by paulobmarcos** [comment]
PR: https://github.com/ipfs-shipyard/js-idm-wallet/pull/9

**Comment by satazor** [comment]
This PR will also contain #119

**Comment by satazor** [comment]
We will implement signing and encryption in a second phase.

**Comment by satazor** [comment]
Reminder to not forget to: subscribe to DID Doc updates in order to remove itself when revoked from another device

**Comment by satazor** [comment]
All of this was taking care of and the PR was merged!
