### ISSUE TITLE
Implement the "locker" scope in the IDM Wallet module

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#11]
## Description

Implement the `locker` scope according to the IDM spec.

## Acceptance Criteria

- [ ] Have the `locker` scope of the IDM Wallet implemented, with support for `passphrases`

## R&D

- Decide if the passphrase weakness should be evaluated in the IDM Wallet; if so, the spec must be updated  
- Decide how the "expiration" works so that the IDM Wallet becomes locked after a certain time

**Comment by paulobmarcos** [comment]
PR: https://github.com/ipfs-shipyard/js-idm-wallet/pull/2
