### ISSUE TITLE
Design "Edit Profile Page"

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#116]
## Description

Predict the prompt with the following details:
- Identity name
- Avatar
- Nationality
- Gender
- Location

## Acceptance Criteria

- [x] Include all the user details
- [x] Have all the radio-button states 
- [x] Have all the select-box (dropdown) states

**Comment by andreforsousa** [comment]
Here's the current status for this, I already had a version for the type of user `person`, please note that fields may vary depending on the choice, type of user, on the identity creation.

We have 3 new components here, radio buttons, select box and a trigger to "use my location". For the last one I'd say that it's not a priority at least for now.

![nomios-edit-profile-01](https://user-images.githubusercontent.com/39052705/57316697-55788580-70ee-11e9-8a55-d0993f595058.jpg)
![nomios-edit-profile-01](https://user-images.githubusercontent.com/39052705/57316706-59a4a300-70ee-11e9-94db-71c0cb7c73e2.jpg)
![nomios-edit-profile-03](https://user-images.githubusercontent.com/39052705/57316708-5b6e6680-70ee-11e9-83da-0e6e695f1d44.jpg)
![nomios-edit-profile-04](https://user-images.githubusercontent.com/39052705/57316715-5e695700-70ee-11e9-8942-644977572497.jpg)
![nomios-edit-profile-05](https://user-images.githubusercontent.com/39052705/57317036-1434a580-70ef-11e9-90d1-5bec46d495e1.jpg)

**Comment by satazor** [comment]
Reviewed and implemented in #118
