### ISSUE TITLE
Implement "Profile Page"

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#117]
## Description
Implement the Profile Page.

## Acceptance Criteria

- [ ] Implement the interface as specified in [#92](https://github.com/ipfs-shipyard/pm-idm/issues/92)

- [ ] Implement a 404 page in case the identity does not exist in the wallet

**Comment by dominguesgm** [comment]
PR open at https://github.com/ipfs-shipyard/nomios-web/pull/12
