### ISSUE TITLE
Implement "Edit Profile Page"

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#118]
## Description

Implement the "Edit Profile Page".

## Acceptance Criteria

- [x] Implement the interface as specified in https://github.com/ipfs-shipyard/pm-idm/issues/116
- [x] Integration with `idm-wallet`

## Pull Request

PR [here](https://github.com/ipfs-shipyard/nomios-web/pull/10)

Related PRs:

- [`<AutocompleteSelect>` component](https://github.com/ipfs-shipyard/nomios-web-uikit/pull/37)
- [`<Radio>` component](https://github.com/ipfs-shipyard/nomios-web-uikit/pull/38)
- [`labelAlignment` prop - `<AvatarPicker>`](https://github.com/ipfs-shipyard/nomios-web-uikit/pull/43)
- [update `<AutocompleteSelect>` to get value from options object](https://github.com/ipfs-shipyard/nomios-web-uikit/pull/44)

**Comment by satazor** [comment]
PR merged: https://github.com/ipfs-shipyard/nomios-web/pull/10
