### ISSUE TITLE
Implement profile data with replication

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#119]
## Description

Implement identity profile details based on Schema.org types (Thing, Person, Organisation)

## Acceptance Criteria

- [x] Should manage profile details about an identity.
- [x] Should be replicated among devices without conflicts and duplications.

**Comment by satazor** [comment]
This is pretty much done but we are still missing tiny details and tests.

**Comment by satazor** [comment]
Done in https://github.com/ipfs-shipyard/js-idm-wallet/pull/9
