### ISSUE TITLE
Design bootstrap page

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#121]
## Description

Design a page that will be shown when entering the page. It should contain a loading & error state, including a retry button.

## Acceptance Criteria

- [x] Have a loading phase
- [x] Have an error phase with a retry page
- [x] Preview any transition animations between this bootstrap page and the wallet

**Comment by andreforsousa** [comment]
Here are the required screens for the loading animation and the `error-state`. Please notice that the .gif file is for preview purposes only, we already have a JSON file which can be used directly from a front-end point of view (using Lottie).

![loading-preview](https://user-images.githubusercontent.com/39052705/57533548-f60cb680-7335-11e9-85eb-f0ce2a5e343d.gif)
![app-error-feedback_01](https://user-images.githubusercontent.com/39052705/57533533-f016d580-7335-11e9-878e-a04f54d39b2e.jpg)
---
![app-error-feedback_detailsapp-error-feedback_02](https://user-images.githubusercontent.com/39052705/57533538-f2792f80-7335-11e9-9752-106af6612729.jpg)

**Comment by satazor** [comment]
This same page can and should be re-used if the identities failed to load().

**Comment by satazor** [comment]
I've already implemented this in https://github.com/ipfs-shipyard/nomios-web/pull/16

Closing!
