### ISSUE TITLE
Integrate create & import with IDM

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#126]
## Description
Both `create new identity` and `import identity` user journies need to be integrated with `idm-wallet`.

## Acceptance Criteria

- [ ] `create new identity` is properly integrated
- [ ] `import identity` is properly integrated

**Comment by satazor** [comment]
Done in https://github.com/ipfs-shipyard/nomios-web/pull/13 and https://github.com/ipfs-shipyard/nomios-web/pull/9
