### ISSUE TITLE
Integrate identities list in the sidebar

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs-shipyard/pm-idm#127]
## Description
The sidebar has an identities list that must be integrated with the `idm-wallet`.
Sidebar design and its variations can be checked in the styleguide.

## Acceptance Criteria

- [ ] The sidebar identities list is properly integrated

**Comment by satazor** [comment]
Done in https://github.com/ipfs-shipyard/nomios-web/pull/13
