### ISSUE TITLE
List devices, social proofs and apps (mocks) in profile

### ISSUE THREAD

**Issue by dominguesgm** [ipfs-shipyard/pm-idm#128]
## Description

List devices, social proofs and apps in an identity's profile page.

## Acceptance Criteria

- [x] Implement the design specified in https://github.com/ipfs-shipyard/pm-idm/issues/92
- [x] Integrate devices with `idm-wallet`; the rest are mocks

**Comment by satazor** [comment]
@dominguesgm I think we may move this to review as well?
