### ISSUE TITLE
Implement Minichat DApp with login/logout support

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#129]
## Description

Implement a Minichat DApp that will be used to test the IDM Client. This same DApp will probably be used for the upcoming workshop that we will do in IPFS Camp. In the first version, we just need to have the capability to login & logout.

## Acceptance Criteria

- [x] Have a Minichat DApp with ability to login & logout

**Comment by satazor** [comment]
This is already done, see https://github.com/ipfs-shipyard/workshop-todo-dapp
