### ISSUE TITLE
Implement the "session" scope without signing

### ISSUE THREAD

**Issue by paulobmarcos** [ipfs-shipyard/pm-idm#131]
## Description

Implement the "session" scope as per the IDM Wallet spec but without signing.

```js
.session.create(App app, String did, { Array<CredentialScope> scopes = [], Number maxAge = 7776000000 } ?options): Promise<Session>
.session.destroy(String sessionId): Promise
.session.isValid(String sessionId): Session
.session.getById(String sessionId): Session
```
## Acceptance Criteria

- [x] Have the ability to get, create, destroy, and verify validity of sessiosn

**Comment by satazor** [comment]
PR: https://github.com/ipfs-shipyard/js-idm-wallet/pull/13
