### ISSUE TITLE
Implement IDM Client as per the spec without signing and verifying 

### ISSUE THREAD

**Issue by paulobmarcos** [ipfs-shipyard/pm-idm#132]
## Description

Implement IDM Client with:

```js
.authenticate({ Array<CredentialScope> scopes = [] } ?options): Promise<Session>
.unauthenticate(): Promise
.getSession(): Promise<Session>
.onSessionChange((Session session) => {}): Function (to remove the listener)
```

## Acceptance Criteria

- [ ] Discuss if it calls `window.open` or with an iframe inside a custom prompt.
- [ ] Add Device Keys to Did Document Authentication List

**Comment by satazor** [comment]
Done, repo: https://github.com/ipfs-shipyard/js-idm-client
