### ISSUE TITLE
Implement signing with sessions and devices

### ISSUE THREAD

**Issue by paulobmarcos** [ipfs-shipyard/pm-idm#136]
## Description

Implement the in the IDM Wallet the ability to sign with sessions and devices.

```js
.session.sign(sessionId, ArrayBuffer data, { SignatureKeyType keyType = 'session', String ?previewUrl } ?options): Promise<IdentifiedSignature>
```
## Acceptance Criteria

- [x] Have the ability to sign with sessions and devices.

**Comment by satazor** [comment]
Done, repos:

- https://github.com/ipfs-shipyard/js-idm-signatures
- https://github.com/ipfs-shipyard/js-idm-client

The IDM spec was updated as well.

**Comment by satazor** [comment]
The previewUrl will be made in a later stage.
