### ISSUE TITLE
Progress report call - 4th June

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#144]
**Date:** 4th June, 16:00 GMT+0
**Notes:** https://cryptpad.fr/code/#/2/code/edit/CeCDbxDBs8+PLwXBGwDsoF-1/
**Call:** https://zoom.us/j/134161591

**Comment by satazor** [comment]
Note to self: I still need to upload the video!

**Comment by catiatpereira** [comment]
Thanks all for participating! 

Notes were saved in the repo: https://github.com/ipfs-shipyard/pm-idm/blob/master/meetings/2019-06-04_progress-report.md
