### ISSUE TITLE
Implement the Subscribe block

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#157]
## Description

Implement the Subscribe block as designed in #114. Note that this task doesn't account for stamp animation.

## Acceptance Criteria

- [x] Implement the subscribe block for desktop
- [x] Implement the subscribe block for tablet
- [x] Implement the subscribe block for phone
- [x] Email should be validated, displaying an error if it failed (empty or invalid)
- [x] Must have submit progress feedback
- [x] Must have submit success feedback
- [x] Must have submit error feedback (API request failed)
- [x] Mock API call with `pDelay()` for now
- [x] Use `react-final-form` and `react-promiseful` for the form & status handling

## To be defined

- [x] Email required and invalid error appearance
- [x] Loading feedback appearance (in the button?)
- [x] Success feedback appearance (in the button?)
- [x] Error feedback appearance (in the button?), including the error message

**Comment by satazor** [comment]
@andreforsousa can you review the "To be defined" and provide us with a answers for these points?

**Comment by andreforsousa** [comment]
We don't have that error and success scenarios yet. I think that we can discuss with the dev team to understand what can be best/faster to tackle at this point.

**Comment by AfonsoVReis** [comment]
@ruimonteiro93 FYI

We should revisit this component since the onsubmit handler is not properly set. Also we must ensure the errors are displaying properly in the component 

I came across this when setting up the api integration for the mailchimp.

**Comment by satazor** [comment]
Done!
