### ISSUE TITLE
Kickstart the IDM UIKit

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#16]
## Description

Kickstart the IDM UIKit, setting up it's repository and all the tooling necessary.

## Acceptance Criteria

- [x] Create `idm-web-uikit` repository
- [x] Setup all the tooling such as `storybook`, `linting` and  `babel`/`webpack`
- [x] Add section explaining how to configure webpack to avoid errors on dev.

## R&D

- [x] Study a way to resolve the build process in the web project when using `npm link`

**Comment by satazor** [comment]
@PedroMiguelSS @DominguesGM Could you update on the missing acceptance criteria? Could we quickly do the README based on the Discussify's styleguide README? I would like to close this task as it is from the previous sprint but we are missing the README.

**Comment by PedroMiguelSS** [comment]
@satazor, the PR is already open here: https://github.com/ipfs-shipyard/idm-web-uikit/pull/1

**Comment by satazor** [comment]
I didn't know about it because it wasn't referenced. I've reviewed it.

**Comment by satazor** [comment]
Merged.
