### ISSUE TITLE
Implement the Footer

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#160]
## Description

Implement the Footer as designed in #114.

## Acceptance Criteria

- [x] Implement the footer for desktop
- [x] Implement the footer for tablet
- [x] Implement the footer for phone
- [x] Build with us should link to: https://github.com/ipfs-shipyard/pm-idm#contributing

## To be defined

- [ ] We don't have a Terms of Usage nor Privacy for now, can we simply remove them?
- [ ] Should "Nomios ©" be changed to "Protocol Labs ©"?

**Comment by satazor** [comment]
@andreforsousa can you review the "To be defined" and provide us with a answers for these points?

**Comment by andreforsousa** [comment]
- We can remove, but we should have this in mind for further releases obviously.
- Nomios as brand is copyrighted, so no. But we add something like "Nomios is sponsored by Protocol Labs", this is something that we can go through Marco or Filipe? I'm not 100% sure.
