### ISSUE TITLE
Integrate mailchimp (or similar) into the Subscribe block

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#166]
## Description

Integrate a mailing list, probably mailchimp, into the Subscribe block. This requires setting up an account and integrate into the project. This task partially depends on #157.

## Acceptance Criteria

- [x] Setup mailing list account
- [ ] Integrate into the project
- [x] We might need to develop a small express server for this

**Comment by satazor** [comment]
We might consider using https://zeit.co/ with a lambda function for this. The free tier would be enough for us: https://zeit.co/pricing.

**Comment by andreforsousa** [comment]
States of success and error already predicted and shared with the team.

**Comment by AfonsoVReis** [comment]
Lambda function can be found here https://github.com/AfonsoVReis/zeit-mailchimp, tell me if you need permissions to access

**Comment by satazor** [comment]
@AfonsoVReis thanks for the code!

We actually ended up using a Gatsby plugin for this.
