### ISSUE TITLE
Design workshop DApp

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#168]
## Description

Design a mini-chat app to be used in the workshop lecture (#169).
 
## Acceptance Criteria

- [x] Must have a header with login + logged in + logout
- [x] Must have a input to type something to write (may have avatar on the left)
- [x] Must show chat messages in reverse order, similar to how a phone displays sms's
- [x] Each message should contain an author (name + avatar), date the body message
- [x] Each message should contain a signature verification; success + fail states
- [x] Optionally, have a list of people present within the chat; alternatively, we must display the number of people within the room
- [ ] ~~Optionally, have a initial screen to type the room name to join~~

**Comment by andreforsousa** [comment]
This is a really simple exercise where we used Google Material Design as starting point. Assets for the required scenarios here:


![logged-in](https://user-images.githubusercontent.com/39052705/59676239-09c1fd00-91bf-11e9-9db9-f05018f490fa.jpg)
![logged-in_input-active](https://user-images.githubusercontent.com/39052705/59676246-0c245700-91bf-11e9-9af7-9bd2a49cb497.jpg)
![logged-out](https://user-images.githubusercontent.com/39052705/59676251-0e86b100-91bf-11e9-97ae-0a8b7c355aa1.jpg)

@satazor you can find the sinal specs here:
https://drive.google.com/open?id=17fKWsV34z93w5w-IMEH-61WaKNNyKLtd
