### ISSUE TITLE
Make IPFS lecture slides & material

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#169]
## Description

Create a Google Slides presentation for the IPFS Camp lecture.

1. Decentralized identity approaches: DIDs, Verifiable Credentials, DID Auth, ... (15m)
2. Nomios presentation (demo + concept explanation)
3. Workshop

## Acceptance Criteria

- [x] Have a Google Slides project with a draft of the contents mentioned above (workshop is just one slide with the link: https://github.com/ipfs-shipyard/idm-chat-workshop)
- [x] Produce the actual workshop material

**Comment by satazor** [comment]
Workshop is fully done at: https://github.com/ipfs-shipyard/idm-chat-workshop
I still need to make a few slides explaning IDM & Nomios, specially the architecture.

**Comment by satazor** [comment]
@joaosantos15 can you put the link to the slides here?

**Comment by satazor** [comment]
As a reminder: decide if we want to stylize these slides, //cc @andreforsousa

**Comment by satazor** [comment]
The slides are done and available here: https://docs.google.com/presentation/d/1HbydOI0w-T_FY23zCACAyHmzDq1ZvyG2tklpPSm6OQQ
