### ISSUE TITLE
Implement the 404 page

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#171]
## Description

Implement the 404 page for when an identity does not exist and integrate it with error bondaries.

## Acceptance Criteria

- [x] Implement 404 page according to the design
- [x] Make use of React Error Boundaries

**Comment by dominguesgm** [comment]
PR open here: https://github.com/ipfs-shipyard/nomios-web/pull/18

**Comment by satazor** [comment]
Already merged!
