### ISSUE TITLE
Create split button and add it to profile page

### ISSUE THREAD

**Issue by dominguesgm** [ipfs-shipyard/pm-idm#174]
## Description

Create the split button, using `dropdown` component, and add it to the profile page

## Acceptance Criteria

- [x] Implement split button according to the designs
- [x] Use it in the profile page

## Pull Requests

[`<SplitButton>`](https://github.com/ipfs-shipyard/nomios-web-uikit/pull/73)

[Split button integration](https://github.com/ipfs-shipyard/nomios-web/pull/28)

### Related PRs

- [Add remove, actions and trash icons](https://github.com/ipfs-shipyard/nomios-web-uikit/pull/72)

**Comment by satazor** [comment]
Dropdown is now available in the uikit, moving this to Todo
