### ISSUE TITLE
Implement Side-by-side hover states

### ISSUE THREAD

**Issue by andreforsousa** [ipfs-shipyard/pm-idm#185]
Implement the hover states for both sections, on mouse-over reveals the description and mouse-out hides it (desktop only).

For the animation, title should go up and button should go down, both with translateY().

All the touch devices should have the description always visible.

**Comment by satazor** [comment]
Reopening this as the button should not be animated, only the title.

Also the title color is incorrect as it should match the green background color (we have CSS variables for that..)

**Comment by dominguesgm** [comment]
Color was changed to celtic, matching the background. Need to discuss with Sousa about the behavior of the button because the last comment doesn't match the description of the task.
