### ISSUE TITLE
Define the final project name

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#19]
## Description

The IDM name is just a codename. We should come up with the final name for the project.

Note that any discussion regarding the final name should **happen privately** because we must buy the domains associated with the name.

## Acceptance Criteria

- [x] Have a final decision for the name of the project

**Comment by marcooliveira** [comment]
Can we schedule a workshop to throw ideas around?

**Comment by satazor** [comment]
@catiatpereira can you organize this?

**Comment by catiatpereira** [comment]
@satazor yes of course!

**Comment by satazor** [comment]
We had a brainstorm session and we settled on a name, follow up on #66
