### ISSUE TITLE
Design the "Lock screen" user-journey

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#20]
## Description

Design a lock screen to be shown when the IDM UI is locked.

## Acceptance Criteria

- [x] User must be able to unlock via a `passphrase`
- [x] Include a message explaining why the wallet is locked and what we are prompting

**Comment by andreforsousa** [comment]
Current version for the journey can be found here:
https://invis.io/PBQEBIWQMGE#/345518860_idm-Lock-Screen_01

Thank you.

**Comment by satazor** [comment]
Seems cool to me! Could you link the animation you showed to us?

**Comment by satazor** [comment]
Also noted that we are still using the old name in a few screens, could you update?

**Comment by satazor** [comment]
All good!
