### ISSUE TITLE
"Why" block carrousel timer is not being canceled correctly when swapping

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#200]
## Description

"Why" block carrousel timer is not being canceled correctly when swapping. Actually, if the user interacts with the carrousel, the automatic sliding should be stopped.

## Acceptance Criteria

- [x] Stop the automatic sliding upon interacting

**Comment by dominguesgm** [comment]
I had a question about the functioning of the slider. Is it supposed to not be possible to interact with the dots?
