### ISSUE TITLE
Improve workshop

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs-shipyard/pm-idm#206]
## Description
The workshop needs to be improved.

## Acceptance Criteria

- [x] Remove (`profile.name || 'Nameless'`)
- [x] Add support for profile images without being a base64 in the profile
- [x] Add loading & error to send message
- [x] Fix [autoprefix error](https://github.com/csstools/postcss-preset-env/issues/133)
- [x] Fix window prompt being resizable
- [x] Update `with-idm` branch

**Comment by satazor** [comment]
@PedroMiguelSS in regards to the window popup being resize, browsers are ignoring the `resizable=0`. We must enforce this via css, by setting a min-weight and min-height.

**Comment by satazor** [comment]
Actually, I made it working by listening to the resize event and correcting the window size. Still, it should be enforced in CSS too. Can you take care of that your branch?

**Comment by PedroMiguelSS** [comment]
I've been taking care of that already in CSS. I did set a fixed width but not a fixed height because it might vary. However, I do still need to add `scroll-y` to the page.

**Comment by satazor** [comment]
For reference: https://github.com/ipfs-shipyard/js-idm-bridge-postmsg/commit/9be86fc2c22a9e9fd6b8970f15292cac5e31aac8

**Comment by satazor** [comment]
The images are now being put on infura as well as on your local node. The URL that comes from the wallet is the infura one but we are now using https://github.com/ipfs-shipyard/react-ipfs-url both in the wallet and in the demo to fetch the images from the local ipfs node!

Pending PR in nomios: https://github.com/ipfs-shipyard/nomios-web/pull/25
