### ISSUE TITLE
Meaningful error in idm-client when we are unable to reach wallet

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs-shipyard/pm-idm#209]
## Description
Instead of showing the standard promised error, show something like: `we are unable to reach the wallet, please make sure it is open`

## Acceptance Criteria

- [x] The wallet has now a meaningful error

**Comment by satazor** [comment]
Done in https://github.com/ipfs-shipyard/js-idm-bridge-postmsg/commit/e176169bda23df6f5e1824982eabff4dfb759204
