### ISSUE TITLE
Implement the "Lock screen" user-journey

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#21]
## Description

Implement the locking screen according to the user-journey.

## Acceptance Criteria

- [x] Implement the locking screen according to the design
- [x] When the locker changes its state to locked or unlocked, react accordingly
- [x] Any access to the IDM wallet while locked should be denied and the lock screen should be displayed
- [x] Any rendered content when locked should not contain any information that is stored encrypted #112 

## R&D

- [x] Think of a way to restore the previous screen exactly with the state we had, e.g.: when editing the profile

**Comment by satazor** [comment]
- Background
- Left and Right padding on the input or container
- Temporary logo morph

**Comment by satazor** [comment]
@dominguesgm can you link the PR here?

**Comment by dominguesgm** [comment]
Sorry it took a while, my bad.
https://github.com/ipfs-shipyard/nomios-web/pull/3
