### ISSUE TITLE
Implement remove app prompt

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs-shipyard/pm-idm#211]
## Description
There must be a prompt whenever a user tries to remove an app.

## Acceptance Criteria

- [x] Define the copy needed with @andreforsousa 
- [x] Implement the prompt in the `styleguide`
- [x] Implement remove app "flow"
- [x] Remove app "flow" is integrated

**Comment by satazor** [comment]
https://github.com/ipfs-shipyard/nomios-web/commit/47340a2185552fa5068ad4ee608506ff118e431d
