### ISSUE TITLE
Progress report call - 18th June

### ISSUE THREAD

**Issue by andreforsousa** [ipfs-shipyard/pm-idm#216]
Date: 18th June, 16:00 GMT+0
Notes: https://cryptpad.fr/code/#/2/code/edit/PmURjkUy8z+HokpWrMaiRN2z/
Call: https://zoom.us/j/134161591

**Comment by catiatpereira** [comment]
Thanks all for participating! 

Notes were saved in the repo: https://github.com/ipfs-shipyard/pm-idm/blob/master/meetings/2019-06-18_progress-report.md
