### ISSUE TITLE
Design the "Create new Identity" user-journey

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#26]
## Description

Design the "Create new Identity" user-journey.

## Acceptance Criteria

- [x] Must give the ability to choose a DID method from a list, where only the IPID is enabled
- [x] Must be a step-by-step in the following order: prompt identity details (name, avatar), prompt device details, "creating..." (loading), save backup (can skip)
- [x] Define what to show when the process ended successfully

**Comment by andreforsousa** [comment]
Current status for this here: https://invis.io/U4QII4KM6CX
Please note that illustrations and some screens might need further revisions/iterations.

Thanks.

**Comment by satazor** [comment]
A few remarks:

- The "AC" initials seem not to be vertically centered
- In the backup flow, the left green part seems to be occupying a lot of space
- When asking for 2 words in the backup confirmation step, the error message should be "The words you selected do not match" or similar

**Comment by satazor** [comment]
Forgot also to mention something during the review today. In the backup flow, when you are asking for the password:

- Change password to passphrase
- The "confirm passphrase" field is not necessary
- I would change the top copy to: Type in the same passphrase you choose when you set up the locker (or something similar)

**Comment by satazor** [comment]
More remarks based on the review we have had yesterday:

- Replace "by coma" with "by spaces"
- Fix "Restore" button not being active when the 12 words are filled
- Remove "Select DID method" for now since we just have one
- Missing "Go back" in some of the screens on the backup process

**Comment by satazor** [comment]
All good!
