### ISSUE TITLE
Design the "Import Identity" user-journey

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#27]
## Description

Design the "Import Identity" user-journey.

## Acceptance Criteria

- [x] Must give the ability to choose a DID method from a list, where only the IPID is enabled
- [x] Must prompt the user for some data present in paper key (few words)
- [x] Define what to show when the process ended successfully (e.g.: either to the identity page or show a successful message saying that the IDM will now sync)

**Comment by andreforsousa** [comment]
Current status for this here: https://invis.io/ASQIQIKJ4V3
Please note that illustrations and some screens might need further revisions/iterations.

Thanks.

**Comment by andreforsousa** [comment]
New version here:
https://invis.io/ASQIQIKJ4V3

Please consider the multiple changes:
- Remove `DID Method` selection
- Include `Did Method` under the imported identity details
- New proposal for the `recovery key`(6 words) 
- Added Loading state between recovery and identity details
  - Loading Button
  - Loading Positive Feedback

**Comment by andreforsousa** [comment]
@satazor As discussed today, here's the new proposal for the "keywords-input":
https://invis.io/ASQIQIKJ4V3

**Comment by andreforsousa** [comment]
The flow was updated following the latest feedback regarding the threshold for the words introduction. The link shared above stays the same.

**Comment by satazor** [comment]
@andreforsousa The new proposal looks great. As a reminder, we should discuss the final copy as the implementation tasks get into the sprint. The reasoning is that we would be deciding it together.

**Comment by satazor** [comment]
All good!
