### ISSUE TITLE
Typography characters 

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#50]
## Description

Ensure that the fonts we are using support a wide range of charsets. If it doesn't, decide on fallback fonts.

## Acceptance Criteria

- [x] Check the charset range of the fonts we chosen and react accordingly

**Comment by andreforsousa** [comment]
We analysed both fonts,`IBM Plex Mono` and `GT Sectra` and they grant support for the following character sets, such as:
- Latin characters: English, Spanish, French, Italian, German, Dutch…
- Latin script: Czech, Polish, Estonian, Lithuanian…
- (non-Latin) Greek/Cyrillic
- Arabic
- Hebrew
- Indic scripts
- Chinese
- Japanese
- Korean
- Russian
