### ISSUE TITLE
Design the shell / chrome of the Nomios UI

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#61]
## Description

The IDM UI concept and also some screens already contain the shell of the application. Still, we should have formalize the design of it.

## Acceptance Criteria

- [x] Must list all the identities associated with the Wallet, serving as a shortcut to enter their pages
- [x] Must account for the number of identities in case they don't fit the screen
- [x] Must include a quick-shortcut to add an identity?
- [x] Must account for a area to place notifications and settings menu

**Comment by andreforsousa** [comment]
Hey guys,
here's the current proposal for the app shell, everything is placed under the sidebar so its easier to use dark or light sections under each page. I'm also sending a WIP prototype with the interaction corresponded to the following screens:
- https://drive.google.com/open?id=1w8Th6tzBRU7WzpK4pGXBWls6NOinwiqB&authuser=andre.sousa@moxy.studio


![nomios-profile-sidebar_1](https://user-images.githubusercontent.com/39052705/54842900-153e7e80-4ccb-11e9-82a7-940c40b93dea.jpg)
![nomios-profile-sidebar_2](https://user-images.githubusercontent.com/39052705/54842905-17a0d880-4ccb-11e9-89ab-3ff1e532e6ce.jpg)
![nomios-profile-sidebar_3](https://user-images.githubusercontent.com/39052705/54842915-196a9c00-4ccb-11e9-9c3c-b54a571e003e.jpg)
![nomios-profile-sidebar_4](https://user-images.githubusercontent.com/39052705/54842920-1bccf600-4ccb-11e9-8f72-14979d4877de.jpg)
![nomios-profile-sidebar_5](https://user-images.githubusercontent.com/39052705/54842924-1e2f5000-4ccb-11e9-8ef1-a002864fa9f2.jpg)
![nomios-profile-sidebar_6](https://user-images.githubusercontent.com/39052705/54842933-2091aa00-4ccb-11e9-88be-dde643a5bb8f.jpg)
![nomios-profile-sidebar_7](https://user-images.githubusercontent.com/39052705/54842936-22f40400-4ccb-11e9-90ad-f5bb49664185.jpg)
![nomios-profile-sidebar_8](https://user-images.githubusercontent.com/39052705/54842941-24bdc780-4ccb-11e9-949c-f3b78f33360e.jpg)
