### ISSUE TITLE
Change IDM name

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#66]
## Acceptance Criteria

- [ ] Change the IDM name to didm 
- [x] Change the UI elements with IDM name to Nomios   
- [x] Register de domain: nomios.io ; nomios.app ; nomios.id

**Comment by satazor** [comment]
I think the renaming to `Nomios` is pretty much done at this point:

- https://github.com/ipfs-shipyard/pm-idm/pull/79
- https://github.com/ipfs-shipyard/nomios-web-uikit/pull/3
- All designs were updated to use Nomios

Regarding renaming IDM to DIDm, I'm not entirely sure. I think DIDm (DID Manager) might cause the impression that the project simply managves DIDs, which is not the case. We manage everything around identities, from their DIDs to their Verifiable Credentials to interactions to issuers/verifiers. What are your thoughts about renaming IDM to DIDm @dominguesgm @PedroMiguelSS @paulobmarcos @joaosantos15?

**Comment by dominguesgm** [comment]
Between those two, I think I still prefer IDM. In any case, it may be nitpicking, but I don't really like the capitalization in DIDm, though I understand it is a way to separate the DID keyword from the "Manager" part.

**Comment by joaosantos15** [comment]
As I mentioned on IRC, my only concern is that there may be a chance of it being seen as us appropriating the DID term... In the sense that calling it DID Manager makes it seem like this is THE manager for DIDs. What are your thoughts on this?

**Comment by satazor** [comment]
Based on all the feedback, I would say to keep IDM. This will also save us some time as it would require renaming a lot of stuff.
