### ISSUE TITLE
IDM Information Architecture

### ISSUE THREAD

**Issue by andreforsousa** [ipfs-shipyard/pm-idm#7]
Hello team,
here's the current status of the IA for the app MVP, after looking at Blockstack and Keybase, alongside with @satazor we've made some decisions considering the number of pages needed, user-journeys, expiration lock and other details features wise.

![idm-mvp-sitemap](https://user-images.githubusercontent.com/39052705/51919298-09c18c00-23db-11e9-98e2-5337cdbc948f.png)

Let me know if you have any suggestions/doubts.
Thank you.

**Comment by satazor** [comment]
@andreforsousa we might want to remove the notification feature for the mvp as it wasn't planned in the IDM workplan and it's an extra overhead we want to avoid for now.

**Comment by andreforsousa** [comment]
Ok @satazor, let's keep the focus form MVP only, added a note on the image and labeled with pink, activity feed will be a nice to have, if there's enough time to do so 👍

![idm-mvp-information-architecture](https://user-images.githubusercontent.com/39052705/52000621-8163e980-24b5-11e9-8c93-92aa1299972d.png)


Thank you.

**Comment by andreforsousa** [comment]
Hello, quick update on this:
- Add "syncing status";
- Categorised multiple items;

![idm-mvp-information-architecture](https://user-images.githubusercontent.com/39052705/52063867-55a33b00-256b-11e9-9c18-9d71038d8736.png)


Thanks.

**Comment by satazor** [comment]
Include the final diagram in the repo, ref: #8

**Comment by andreforsousa** [comment]
Thanks André. Please consider this as the most updated one, to grant more consistency across journeys the naming conventions were revised. Also added other identity types, such as: ```Person```; ```Organization``` and ```Other```, with their own details.


![idm-mvp-information-architecture](https://user-images.githubusercontent.com/39052705/52475135-720a2d80-2b92-11e9-8923-48281811e5d1.png)

**Comment by satazor** [comment]
Thank you @andreforsousa, the diagram was added to the repository and it's part of the concept paper too.

We will link this diagram in the README too.
