### ISSUE TITLE
Include the "Logo Icon" in the styleguide

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#70]
## Description

Include the "Logo Icon" component in the styleguide. This task depends on #18.

## Acceptance Criteria

- [ ] Have the "Logo Icon" component in the styleguide document.

**Comment by satazor** [comment]
Blocked by #18

**Comment by andreforsousa** [comment]
I may include at the least the vertical and horizontal variants, since #18 only needs to be reviewed to advance, what do you say @satazor ? Thank you.
