### ISSUE TITLE
Include the Button feedback in the styleguide

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#71]
## Description

Include the button's success, loading and error states in the styleguide.

## Acceptance Criteria

- [x] Include the button's success, loading and error states in the styleguide

**Comment by satazor** [comment]
@PedroMiguelSS @dominguesgm can you review this and close the issue if it's all good?

**Comment by PedroMiguelSS** [comment]
All good. Closing this as it's already designed in the styleguide.
