### ISSUE TITLE
Implement feedback on Button component in UIKit

### ISSUE THREAD

**Issue by catiatpereira** [ipfs-shipyard/pm-idm#73]
## Description

Implement the Feedback component in UIKit

## Acceptance Criteria

- [x]  Have the <Feedback> component as defined in #71 

## R&D

- [x] Investigate if we can port the loading animation from moxy.studio or https://codepen.io/Rplus/pen/lEDBj

**Comment by satazor** [comment]
PR: https://github.com/ipfs-shipyard/nomios-web-uikit/pull/4
