### ISSUE TITLE
Predict animations for all Modal variants

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#74]
## Description

There are several types of modal variants. The goal of this task is to define the animations of the content and do the hand-off to the dev team

## Acceptance Criteria

- [x] Define the animations of the modal contents
- [x] Define a common language for the different types
- [x] Predict how the user can close a modal that can be closed (X?), including its animation

**Comment by satazor** [comment]
Based on the review, what's missing is the close animation.

**Comment by andreforsousa** [comment]
Hello team!

Here are the animations for the modal "structure", already considered the entrance and close, for both `half` and `wide` layout, these are following the same treatments and also I've tried to reverse the animation when closing to help with the implementation constrains. If needed these could be revisited afterwards, but I'd say they're good at least for the MVP.

- Modal Entrance to Full
https://drive.google.com/open?id=1vsUJajhADHeucTAjg4YhSW5d2xBVLcRT&authuser=andre.sousa@moxy.studio

- Modal Close (half)
https://drive.google.com/open?id=1vlNYwfqKeBOnu-7drmhtkJfxAHAusdQU

- Modal Close (wide)
https://drive.google.com/open?id=1v_yP30kP4bN6N4wRO2KBPZ9kEbt6DY6s

- Modal Half Bordered to Wide
https://drive.google.com/open?id=1vbBxN2BI-7VZZrMENpl3dg8tX0bUlZ4W



@satazor @PedroMiguelSS @dominguesgm 


Thank you!
