### ISSUE TITLE
Update Storybook to version 5

### ISSUE THREAD

**Issue by dominguesgm** [ipfs-shipyard/pm-idm#81]
## Description

Update the storybook version of `nomios-web-uikit` from version 4 to version 5.

## Acceptance Criteria

- [x] `nomios-web-uikit` now runs Storybook 5

**Comment by satazor** [comment]
We are already using v5: https://github.com/ipfs-shipyard/nomios-web-uikit/blob/11b2ea42a431a93a180310055f651f94d52893d1/package.json#L50
