### ISSUE TITLE
Add modal flow variants to the styleguide

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#85]
## Description

We had a discussion last week where we defined 3 different flows inside modals. Include them in the styleguide

## Acceptance Criteria

- [x] Include the different modal flows in the styleguide

**Comment by andreforsousa** [comment]
Hello,
following the discussion about the `ModalFlow` here's the documentation within the styleguide.

Any question let me know,
thanks.

![Molecules](https://user-images.githubusercontent.com/39052705/54695814-90b0fc00-4b22-11e9-9d40-b3bce9c37014.jpg)
