### ISSUE TITLE
Design the "Setup locker" user-journey

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#9]
## Description

Design the "Setup locker" screen.

## Acceptance Criteria

- [x] Must explain what is the locker and why is necessary (used to decrypt the local storage)
- [x] Ability to define a passphrase
- [x] Display a passphrase strength indicator and restrictions
- [x] Display any error during this process (e.g.: trying to advance with a weak passphrase)

## R&D

- [x] Think about that to display when the user completes this step: should we show the "Homepage" screen with "Next steps" or display the "Next Steps" in this flow?

**Comment by andreforsousa** [comment]
Current version for the journey can be found here:
https://invis.io/6CQD811QRXS#/345241302_setup-Locker_1-01

Thank you.

**Comment by satazor** [comment]
Closing as it was reviewed and and implemented.
