### ISSUE TITLE
Design Identity Profile page

### ISSUE THREAD

**Issue by andreforsousa** [ipfs-shipyard/pm-idm#92]
## Description

Draft an initial version of the Identity Profile page, using the latest version of the app shell.

## Acceptance Criteria

Have defined all the four required sections:
- [x] User details
- [x] Devices
- [x] Social Proofs
- [x] Apps

**Comment by andreforsousa** [comment]
Here's the current version, with a new illustration for the `apps-spotlight`.
I'm already exposing on the spotlight the four social proofs.

Regarding this I still need to define the details pages for: Devices, Social Proofs and Apps, I'm not sure if this should be treat as a different card or should I place everything here once the're finished, any thoughts @satazor? Thank you.

![nomios-profile-page-1](https://user-images.githubusercontent.com/39052705/55074484-4ed70700-5088-11e9-804b-f8637899e72c.jpg)
![nomios-profile-page-2](https://user-images.githubusercontent.com/39052705/55074485-4ed70700-5088-11e9-8f04-e278177f24f6.jpg)
![nomios-profile-page-3](https://user-images.githubusercontent.com/39052705/55074486-4f6f9d80-5088-11e9-8c23-72661cb715ef.jpg)

**Comment by satazor** [comment]
- Contrast of boxes
- "View all" counter for each box

**Comment by andreforsousa** [comment]
A few notes regarding the spotlights:
- "My Apps" link is disable if there's no any app used yet;
- On the "My devices" spotlight the title is the only interactive UI element, all information regarding a specific device works only as an overview;
- Social proofs can be claimed through each available link on its spotlight;
- No more hover states for the spotlights background, following the decisions mentioned above, this will no longer compete with the interaction given on the links title;
- I'm still a bit unsure of the treatment on the "My apps", if it could be somehow different from the other ones on its empty state.

Thanks.

![nomios-profile-page-3-1](https://user-images.githubusercontent.com/39052705/55870469-8feb1300-5b80-11e9-9a2a-0881c9ceef71.jpg)
![nomios-profile-page-3-2](https://user-images.githubusercontent.com/39052705/55870484-95e0f400-5b80-11e9-970e-2ac3a30e9872.jpg)
![nomios-profile-page-3-3](https://user-images.githubusercontent.com/39052705/55870495-9c6f6b80-5b80-11e9-85bf-d4c5a074b7c6.jpg)
![nomios-profile-page-3-4](https://user-images.githubusercontent.com/39052705/55870499-a09b8900-5b80-11e9-901c-1b5298bace18.jpg)
![nomios-profile-page-3-5](https://user-images.githubusercontent.com/39052705/55870508-a2fde300-5b80-11e9-8ff0-70b8286620bd.jpg)
![nomios-profile-page-3-5](https://user-images.githubusercontent.com/39052705/55870509-a4c7a680-5b80-11e9-98af-2f7605ac5888.jpg)
![nomios-profile-page-3-6](https://user-images.githubusercontent.com/39052705/55870985-a8a7f880-5b81-11e9-996f-f71d2741c07a.jpg)
