### ISSUE TITLE
Adjust modals for the different resolutions

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#93]
## Description

Decide and implement adjustments for the modals according to different resolutions, greater than 1024.

## Acceptance Criteria

- [x] Define the min-width and min-height of the web app
- [x] Define the adjustments necessary for the modal
- [x] Implement those adjustments in modal
- [x] Implement those adjustments in the web app

**Comment by PedroMiguelSS** [comment]
#### Web app

`min-width`: 102.4rem
`min-height`: 70rem

#### Modal

`min-width`: 97.4rem
`max-width`: 128rem
`height`: 65rem

#### Moda Flow

left-content `min-width`: 33.4rem
right-content `width`: 64rem ⚠️fixed!
