### ISSUE TITLE
Decide the morph of the brand symbol into a lock icon in the Lock Screen

### ISSUE THREAD

**Issue by satazor** [ipfs-shipyard/pm-idm#94]
## Description
Prepare the animation between the `brand-symbol` to the `lock-icon` and the decide the best handoff format to the dev team. 

## Acceptance Criteria

- [x] Brand-symbol is converted to outline
- [x] Tween between `brand-symbol-outline` and `brand-symbol`
- [x] Morph or deconstruct + construct both icons into one animated sequence only.
- [x] Have a reasonable format to handoff

**Comment by andreforsousa** [comment]
Hello,
everything on this is already accomplished, we've decided to go with a JSON file, reproduced from Bodymovin which you can preview here: https://lottiefiles.com/preview (You only need to drag this [brand-symbol-to-lock-icon file](https://drive.google.com/open?id=1804Uq1q5xEe3WH5HRvFjrCFsWexknscO) to understand how the final result looks like).

I think this will require way less work from the implementation side, you only need to add Lottie / Bodymovin libraries to the project.

Thanks!


@dominguesgm @PedroMiguelSS @satazor @paulobmarcos

**Comment by satazor** [comment]
This is already implemented, closing this as completed.
