### ISSUE TITLE
Add illustrations in the styleguide

### ISSUE THREAD

**Issue by andreforsousa** [ipfs-shipyard/pm-idm#99]
## Description

Extract all illustrations from the flows and pages to add them in the styleguide and display if there's more than one color on each of them.

## Acceptance Criteria

- [x] Merge all the illustration paths so that the SVGs can be lighter once exported;
- [x] Export with `style-elements` option, so that illustrations with more than one color can be tweaked on the implementation side;

**Comment by satazor** [comment]
Done!
